# **Multiple Linear Regression using Train-Test Split**

In [4]:
# Importing Libraries

import pandas as pd

In [1]:
from google.colab import files
uploaded=files.upload()

Saving 50_Startups.csv to 50_Startups.csv


In [5]:
startup=pd.read_csv("50_Startups.csv")

In [6]:
startup.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
df=startup.rename({'R&D Spend':'RDS','Administration':'Admin','Marketing Spend':'MS'},axis=1)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RDS     50 non-null     float64
 1   Admin   50 non-null     float64
 2   MS      50 non-null     float64
 3   State   50 non-null     object 
 4   Profit  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [9]:
df.head()

RDS      Admin         MS       State     Profit
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

In [10]:
df.corr()

RDS     Admin        MS    Profit
RDS     1.000000  0.241955  0.724248  0.972900
Admin   0.241955  1.000000 -0.032154  0.200717
MS      0.724248 -0.032154  1.000000  0.747766
Profit  0.972900  0.200717  0.747766  1.000000

In [12]:
df.columns

Index(['RDS', 'Admin', 'MS', 'State', 'Profit'], dtype='object')

In [13]:
X=df.iloc[:,0:3]
y=df.iloc[:,-1]

In [17]:
# Importing train_test_split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=0)

In [18]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((33, 3), (17, 3), (33,), (17,))

In [19]:
X.describe()

RDS          Admin             MS
count      50.000000      50.000000      50.000000
mean    73721.615600  121344.639600  211025.097800
std     45902.256482   28017.802755  122290.310726
min         0.000000   51283.140000       0.000000
25%     39936.370000  103730.875000  129300.132500
50%     73051.080000  122699.795000  212716.240000
75%    101602.800000  144842.180000  299469.085000
max    165349.200000  182645.560000  471784.100000

In [20]:
array1=X_train.values

In [22]:
# Scaling our data

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train[['RDS','Admin','MS']]=scaler.fit_transform(array1)

In [23]:
X_train

RDS     Admin        MS
45 -1.418591  0.080072 -1.462801
48 -1.428047 -2.751057 -1.477200
29 -0.085243  1.209202 -0.666887
15  0.924349  0.020008  0.502677
30 -0.159768 -0.252727 -0.787953
32 -0.130578  0.278168 -1.128647
16  0.170831 -0.019845  0.522113
42 -0.951324 -1.013260 -0.357832
20  0.134523 -0.322087  0.781672
43 -1.119221  0.206331 -1.208447
8   1.048569  1.040565  0.879607
13  0.459340  0.523530  0.433766
25 -0.104659  0.682195 -0.433756
5   1.282492 -0.871524  1.267208
17  0.514337  0.898193  0.659978
40 -0.845791 -0.139154 -0.170305
49 -1.439234 -0.200236 -1.135546
1   1.916520  1.144515  1.880112
12  0.497962  0.203910  0.412396
37 -0.529701 -2.769043  0.012981
24  0.150830 -0.892378 -0.413999
6   1.339012  0.981132 -0.511247
23 -0.045472 -0.639422  0.827840
36 -0.847660  0.193582  0.043971
21  0.178598  1.238189  0.789786
19  0.344329  1.228050 -1.477200
9   1.106199 -0.524936  0.829450
39 -0.643449 -1.529657 -0.153638
46 -1.412085 -0.245887  0.769949
3   1.540380 -0.134235  1.421032
0   1.973307  0.578374  2.091018
47 -1.439234  0.520865 -1.477200
44 -0.981521  1.278566 -1.262898

In [24]:
array2=X_test.values

In [25]:
X_test[['RDS','Admin','MS']]=scaler.fit_transform(array2)
X_test

RDS     Admin        MS
28 -0.408135  1.995672 -1.400487
11  0.508950 -0.892589  0.093304
10  0.541827 -0.294829 -0.140347
41 -1.418944 -1.117656 -0.874666
2   1.906800 -0.595197  1.888967
27 -0.247711  0.254195  1.267475
38 -1.621944 -1.714123 -0.638622
31 -0.538335  1.043770 -1.740231
22 -0.197726  0.092645  0.701447
4   1.606561 -0.905268  1.414867
33 -0.687801 -0.534417 -0.305238
35 -0.938922 -1.106953 -0.408729
26 -0.162380  0.771460 -1.219980
34 -0.928007  1.202464 -0.348794
18  0.272588 -0.180969  0.606099
7   1.293738  0.815778  0.934800
14  1.019441  1.166017  0.170134

In [35]:
print("Scaled Training DataFrame\n",X_train,"\n\nScaled Testing DataFrame\n",X_test) 

Scaled Training DataFrame
          RDS     Admin        MS
45 -1.418591  0.080072 -1.462801
48 -1.428047 -2.751057 -1.477200
29 -0.085243  1.209202 -0.666887
15  0.924349  0.020008  0.502677
30 -0.159768 -0.252727 -0.787953
32 -0.130578  0.278168 -1.128647
16  0.170831 -0.019845  0.522113
42 -0.951324 -1.013260 -0.357832
20  0.134523 -0.322087  0.781672
43 -1.119221  0.206331 -1.208447
8   1.048569  1.040565  0.879607
13  0.459340  0.523530  0.433766
25 -0.104659  0.682195 -0.433756
5   1.282492 -0.871524  1.267208
17  0.514337  0.898193  0.659978
40 -0.845791 -0.139154 -0.170305
49 -1.439234 -0.200236 -1.135546
1   1.916520  1.144515  1.880112
12  0.497962  0.203910  0.412396
37 -0.529701 -2.769043  0.012981
24  0.150830 -0.892378 -0.413999
6   1.339012  0.981132 -0.511247
23 -0.045472 -0.639422  0.827840
36 -0.847660  0.193582  0.043971
21  0.178598  1.238189  0.789786
19  0.344329  1.228050 -1.477200
9   1.106199 -0.524936  0.829450
39 -0.643449 -1.529657 -0.153638
46 -1.412085 -0.

In [37]:
from sklearn.linear_model import LinearRegression
regressor_best=LinearRegression()
regressor_best.fit(X_train,y_train)

LinearRegression()

In [38]:
regressor_best

LinearRegression()

In [39]:
regressor_best.intercept_

108167.60515151516

In [40]:
regressor_best.coef_

array([38869.19865987,  1459.93304966,  4061.28095628])

In [50]:
y_pred_test=regressor_best.predict(X_test)
y_pred_test

array([ 89529.51827432, 127025.90776687, 128227.57390025,  47830.41230908,
       189086.05314355, 104057.95800824,  40027.83008332,  81699.21608588,
       103466.18561625, 175037.87932788,  79413.44635343,  68396.42205646,
        98027.60791125,  72435.6912579 , 120960.22127044, 163441.65120028,
       150185.71301034])

In [51]:
print(y_test)

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
33     96778.92
35     96479.51
26    105733.54
34     96712.80
18    124266.90
7     155752.60
14    132602.65
Name: Profit, dtype: float64


In [52]:
y_pred_train=regressor_best.predict(X_train)
y_pred_train

array([ 47204.16160196,  42644.87034024, 103911.22452747, 146167.01589551,
        98388.48793162,  98914.51709732, 116899.13301914,  68257.8746172 ,
       116100.75332254,  60057.77185287, 154016.13435507, 128547.76529913,
       103333.95798858, 161891.1835084 , 132151.13085036,  74397.56893537,
        47321.62360827, 191967.79294882, 129495.55400006,  83588.63642009,
       111046.0681656 , 159569.99680707, 108828.73623816,  75680.91839533,
       120124.78585562, 117344.94688741, 153766.93054402,  80300.10571425,
        56048.9824064 , 173616.16336925, 194205.05889633,  46986.82641   ,
        66754.29219056])

In [53]:
print(y_train)

45     64926.08
48     35673.41
29    101004.64
15    129917.04
30     99937.59
32     97427.84
16    126992.93
42     71498.49
20    118474.03
43     69758.98
8     152211.77
13    134307.35
25    107404.34
5     156991.12
17    125370.37
40     78239.91
49     14681.40
1     191792.06
12    141585.52
37     89949.14
24    108552.04
6     156122.51
23    108733.99
36     90708.19
21    111313.02
19    122776.86
9     149759.96
39     81005.76
46     49490.75
3     182901.99
0     192261.83
47     42559.73
44     65200.33
Name: Profit, dtype: float64


In [54]:
import numpy as np

In [58]:
from sklearn.metrics import r2_score

R2_train=r2_score(y_train,y_pred_train)
R2_test=r2_score(y_test,y_pred_test)

print("R-squared Train",np.round(R2_train,5),"\nR-squared Test",np.round(R2_test,5))

R-squared Train 0.95544 
R-squared Test 0.63422


In [65]:
rsq=pd.DataFrame({'Test':['Training','Testing'],'R-Squared':[np.round(R2_train,5),np.round(R2_test,5)]})
rsq

Test  R-Squared
0  Training    0.95544
1   Testing    0.63422